Classes and objects tests
Kleo5522/Csharp-Unit-Tests pull request #4
Opened 2021-05-20 17:21 UTC by Kleo5522

Classes and Objects homework.

2021-05-21 17:34 UTC, ausmoons commented on ClassesAndObjectsTestsTests/Exercise1Tests.cs
> +        public void Exercise1Test_ChangePrice20Point47AndQuantity10_ReturnStringNewPrice20Point47And10Quantity()
PrintProduct_ChangePrice20Point47AndQuantity10_ReturnStringNewPrice20Point47And10Quantity

2021-05-21 17:35 UTC, ausmoons requested changes
Izlabo namingu Metode_KoPadod_KoSagaida

2021-05-24 15:42 UTC, ausmoons commented on ClassesAndObjectsTestsTests/Exercise12Tests.cs
> +        public void Deposit_Balance120Deposit50Point99_ReturnsBalance170Point99()
Kādu metodi tu te testē?

2021-05-24 15:43 UTC, Kleo5522 commented on ClassesAndObjectsTestsTests/Exercise12Tests.cs
> +        public void Deposit_Balance120Deposit50Point99_ReturnsBalance170Point99()
Deposit Metodi.

2021-05-24 16:20 UTC, ausmoons approved these changes

2021-05-24 16:21 UTC, merged